// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPUSUl9KMK8MO_YYWSnPFqurOlmeNhsw',
    appId: '1:45350779088:android:70db9905dac9dba3dc46d5',
    messagingSenderId: '45350779088',
    projectId: 'da2-chien-1eac1',
    databaseURL: 'https://da2-chien-1eac1-default-rtdb.firebaseio.com',
    storageBucket: 'da2-chien-1eac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshU0O8vv-oVHHwZVZC4z2xiXgFfyIhu0',
    appId: '1:45350779088:ios:0da430b112116333dc46d5',
    messagingSenderId: '45350779088',
    projectId: 'da2-chien-1eac1',
    databaseURL: 'https://da2-chien-1eac1-default-rtdb.firebaseio.com',
    storageBucket: 'da2-chien-1eac1.appspot.com',
    iosBundleId: 'com.example.ktmm',
  );
}
