// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjLcayPVjaqHCpAiwNxfXLmcoQZeCyZgI',
    appId: '1:894948798625:android:acad6fee1b5a36664fc0e0',
    messagingSenderId: '894948798625',
    projectId: 'ktmmn-fb2f7',
    databaseURL: 'https://ktmmn-fb2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ktmmn-fb2f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaVNjjCdHEO9fx_mi45OjQ0njXzWadeY',
    appId: '1:894948798625:ios:0906f5ac0384e8c34fc0e0',
    messagingSenderId: '894948798625',
    projectId: 'ktmmn-fb2f7',
    databaseURL: 'https://ktmmn-fb2f7-default-rtdb.firebaseio.com',
    storageBucket: 'ktmmn-fb2f7.appspot.com',
    iosBundleId: 'com.example.ktmm',
  );
}
